from django.core.management.base import BaseCommand
from codigoQR.apps.home.models import Grados, Estudiantes

def insert_data():
	once_b = Grados(nombregrado = '11B')
	once_b.save()
	siete_a = Grados(nombregrado = '7A')
	siete_a.save()
	directivo = Grados(nombregrado = 'Directivo')
	directivo.save()
	Estudiantes(nombre = 'ANDRES FELIPE POSSOS LOZANO', identificacion = '1000066468', grado = once_b).save()
	Estudiantes(nombre = 'FABIAN MANUEL GIL CAMACHO', identificacion = '1003516299', grado = once_b).save()
	Estudiantes(nombre = 'LAURA ISABEL GOMEZ DONCEL', identificacion = '1001347821', grado = once_b).save()
	Estudiantes(nombre = 'ANA VICTORIA AGUIRRE ARCOS', identificacion = '1072098803', grado = siete_a).save()
	Estudiantes(nombre = 'KAROLL JIZETH ALVIZ VALDERRAMA', identificacion = '1072099062', grado = siete_a).save()
	Estudiantes(nombre = 'JUAN MANUEL AMAYA ALVAREZ', identificacion = '1032939357', grado = siete_a).save()
	Estudiantes(nombre = 'MARIA JOSE BANGUERO VANEGAS', identificacion = '1071062650', grado = siete_a).save()
	Estudiantes(nombre = 'JUAN CAMILO BARRAGAN CALDERON', identificacion = '1070593976', grado = siete_a).save()
	Estudiantes(nombre = 'MARIA JOSE BARRERO HERRERA', identificacion = '1014859103', grado = siete_a).save()
	Estudiantes(nombre = 'JUANITA BARRERO SIERRA', identificacion = '1071062332', grado = siete_a).save()
	Estudiantes(nombre = 'PAULA VANESSA CALDERON GAVIRIA', identificacion = '1014596456', grado = siete_a).save()
	Estudiantes(nombre = 'LAURA VANESSA CELIS ALDANA', identificacion = '1072099315', grado = siete_a).save()
	Estudiantes(nombre = 'SOFIA VALENTINA CORTES DELGADO', identificacion = '1014979817', grado = siete_a).save()
	Estudiantes(nombre = 'BRIAN STEVEN CORTES DIAZ', identificacion = '1070591469', grado = siete_a).save()
	Estudiantes(nombre = 'LAURA SOFIA CRUZ BARRERO', identificacion = '1072099614', grado = siete_a).save()
	Estudiantes(nombre = 'NICOL VALERIA DIAZ RODRIGUEZ', identificacion = '1072098855', grado = siete_a).save()
	Estudiantes(nombre = 'ZHARICK DIAZ ROJAS', identificacion = '1070590648', grado = siete_a).save()
	Estudiantes(nombre = 'MARIA JOSE GALINDO HERRERA', identificacion = '1072099088', grado = siete_a).save()
	Estudiantes(nombre = 'VANESSA GARAY HERNANDEZ', identificacion = '1054545763', grado = siete_a).save()
	Estudiantes(nombre = 'ALLISON ALEXANDRA GARCIA LOSADA', identificacion = '1105674300', grado = siete_a).save()
	Estudiantes(nombre = 'JOSE MIGUEL GIRALDO ZULUAGA', identificacion = '1038406327', grado = siete_a).save()
	Estudiantes(nombre = 'ZHARICK VALENTINA GOMEZ PAVA', identificacion = '1072099432', grado = siete_a).save()
	Estudiantes(nombre = 'KEVIN FELIPE GUATAVITA ULLOA', identificacion = '1070594830', grado = siete_a).save()
	Estudiantes(nombre = 'NIKOL LAGUNA CAPERA', identificacion = '1070595130', grado = siete_a).save()
	Estudiantes(nombre = 'MARIANA LEAL URUEÑA', identificacion = '1070596320', grado = siete_a).save()
	Estudiantes(nombre = 'VALENTINA JULIETH MONTERROSA RONDON', identificacion = '1091203049', grado = siete_a).save()
	Estudiantes(nombre = 'JUAN DAVID PATOA RODRIGUEZ', identificacion = '1072099788', grado = siete_a).save()
	Estudiantes(nombre = 'MARIANA CAMILA PAVA CASTILLO', identificacion = '1070591717', grado = siete_a).save()
	Estudiantes(nombre = 'SERGIO ANDRES PRIETO NUÑEZ', identificacion = '1070591844', grado = siete_a).save()
	Estudiantes(nombre = 'DANIEL RICARDO RAQUEJO GARCIA', identificacion = '1071062073', grado = siete_a).save()
	Estudiantes(nombre = 'ANA MARIA RIVEROS GAVIRIA', identificacion = '1070589294', grado = siete_a).save()
	Estudiantes(nombre = 'MARIANA SOFIA SANCHEZ DONCEL', identificacion = '1070594212', grado = siete_a).save()
	Estudiantes(nombre = 'JUAN FELIPE SANCHEZ ORTIZ', identificacion = '1016949248', grado = siete_a).save()
	Estudiantes(nombre = 'ANDRES DAVID SERRANO POSADA', identificacion = '1072099359', grado = siete_a).save()
	Estudiantes(nombre = 'LAURA SOFIA SUAREZ GARCIA', identificacion = '1072099122', grado = siete_a).save()
	Estudiantes(nombre = 'JUAN DAVID SUAREZ', identificacion = '1070586901', grado = siete_a).save()
	Estudiantes(nombre = 'MARIANA TORRES CARDENAS', identificacion = '1072099171', grado = siete_a).save()
	Estudiantes(nombre = 'MARIANA TOVAR GUERRA', identificacion = '1072099482', grado = siete_a).save()
	Estudiantes(nombre = 'JUAN DAVID TOVAR OSPINA', identificacion = '1070588636', grado = siete_a).save()
	Estudiantes(nombre = 'JOHAN ALEXANDER VALDERRAMA BARBERI', identificacion = '1011092852', grado = siete_a).save()
	Estudiantes(nombre = 'SAMUEL DAVID VALENCIA GRANADOS', identificacion = '1072098931', grado = siete_a).save()
	Estudiantes(nombre = 'NICOLAS FELIPE VERA GALEANO', identificacion = '1070593271', grado = siete_a).save()
	Estudiantes(nombre = 'Christián Alejandro Barberi Ibañez', identificacion = '1070599276', grado = directivo).save()

class Command(BaseCommand):
	def handle(self, **options):
		insert_data()