# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-09 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombregrado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso_salida', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(max_length=1)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Estudiantes')),
            ],
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grados'),
        ),
    ]
